server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://apiserver:8191/api/;
        proxy_set_header Host $host;
    }

    location /artifacts/ {
        proxy_pass http://minio:9000/drop/;
        proxy_set_header Host $host;
        proxy_buffering off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
